"""Remove user-specific anomaly columns

Revision ID: 49f901b7d83d
Revises: 746e2c628a70
Create Date: 2025-07-10 05:48:30.099828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f901b7d83d'
down_revision: Union[str, Sequence[str], None] = '746e2c628a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_activity', 'user_anomaly_reason')
    op.drop_column('login_activity', 'is_user_specific_anomaly')
    op.drop_column('login_activity', 'user_anomaly_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_activity', sa.Column('user_anomaly_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('login_activity', sa.Column('is_user_specific_anomaly', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('login_activity', sa.Column('user_anomaly_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
