"""add failed login tracking to user

Revision ID: a2b54f2ecb7a
Revises: b3932ef2d75d
Create Date: 2025-07-10 21:28:15.876082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b54f2ecb7a'
down_revision: Union[str, Sequence[str], None] = 'b3932ef2d75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('lockout_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lockout_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
