"""Add country and asn to login_activity

Revision ID: ca13aa9eebb0
Revises: 49f901b7d83d
Create Date: 2025-07-10 06:04:42.804162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca13aa9eebb0'
down_revision: Union[str, Sequence[str], None] = '49f901b7d83d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_activity', sa.Column('country', sa.String(), nullable=True))
    op.add_column('login_activity', sa.Column('asn', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_activity', 'asn')
    op.drop_column('login_activity', 'country')
    # ### end Alembic commands ###
