services:
  - type: web
    name: chatbot-backend
    env: node
    plan: free
    buildCommand: |
      npm install
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chatbot-db
          property: connectionString
    healthCheckPath: /health

databases:
  - name: chatbot-db
    databaseName: chatbot_db
    user: admin
    plan: free