services:
  - type: web
    name: chatbot-backend
    env: node
    plan: free
    buildCommand: |
      cd backend
      npm install
      npm run build
    startCommand: |
      cd backend
      npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chatbot-db
          property: connectionString
    healthCheckPath: /health